# spring
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/study/spring-data-jpa-querydsl/db/querydsl
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true # 주석으로 jpql 이 출력된다.
#        default_batch_fetch_size: 100


# logging
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace